services:
  mysql:
    image: mysql:8.0
    container_name: commerce-local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: commerce
      MYSQL_USER: commerce-user
      MYSQL_PASSWORD: commerce-password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data_local:/var/lib/mysql
networks:
  commerce-server: